### ISSUE TITLE
Add support for Linux, maybe publish on Flathub

### ISSUE THREAD

**Issue by GabMus** [UnicornsOnLSD/finamp#40]
Hi, I just tried Finamp and I gotta say it's a pretty great way to listen to Jellyfin music. I was wondering if you wanted to add support for Linux, since this is built with Flutter. This way we could use it on our desktop PCs as well as on the new Linux phones.

Publishing on Flathub would be an added value, you can look at [Fluffy chat](https://flathub.org/apps/details/im.fluffychat.Fluffychat) as an example for another Flutter app that has been published on Flathub.

**Comment by UnicornsOnLSD** [comment]
I'd love to create a Linux version, but not all Flutter packages run on all platforms. Many use platform code to use native Android/iOS stuff. Here are all of the packages that are currently incompatible with Linux:

* device_info (Used to give Jellyfin device info)
* package_info (Used to give Jellyfin device info)
* cached_network_image (Image widget that automatically caches image to save bandwidth)
* just_audio/audio_service/audio_session (The packages that handle audio playback)
* flutter_downloader (Handles downloads)
* file_picker (Used to select custom directories)
* permission_handler (Used to request storage permissions for external directories)

The only packages that are really essential there are the audio packages. I could probably create a desktop interface for device_info and package_info. On desktop, caching images isn't so important, so I could use the normal image widget on desktop. Downloading songs isn't so important on desktop, which would remove the need for file_picker too. permission_handler won't be needed on desktop (it might on macOS, but this issue is about Linux). Of course, this still means that the app won't work on desktop in its current state, unless you want a music player that doesn't play music. The audio packages are actually supported on macOS, so I might work on some desktop stuff for a potential macOS release.

**Comment by GabMus** [comment]
As I mentioned in the PR, I'm not a dart/Flutter developer, but maybe one could re-implement those interfaces to work on Linux? Or possibly request Linux support for the original libraries?

**Comment by UnicornsOnLSD** [comment]
Windows/Linux support is being worked on for just_audio. The issue can be viewed at https://github.com/ryanheise/just_audio/issues/103. They're working on using VLC for the backend. For audio_service, a "default audio service" was added since Desktop doesn't rely on platform stuff for background playback (https://github.com/ryanheise/audio_service/issues/609/https://github.com/ryanheise/audio_service/pull/632). audio_session may not be required, since that package is meant for configuring the audio player for pausing during calls and stuff.

I might have a look at contributing to the just_audio issue, and I might look into adding MPRIS (and whatever Windows uses) support to audio_service, since the default implementation doesn't really do anything special. No promises though :p

**Comment by GabMus** [comment]
Any work is highly appreciated! Besides if someone else wants to jump in and contribute, this is already a start :)

**Comment by UnicornsOnLSD** [comment]
device_info and package_info could be replaced by the "plus" packages that both have desktop support. https://plus.fluttercommunity.dev/

**Comment by UnicornsOnLSD** [comment]
Since everything but flutter_downloader worked on macOS, I tried a macOS version. It technically works, but I've basically just commented out everything related to downloading, which makes the app a bit janky. There are some other issues, such as the settings stuff not loading properly and the progress bar not working. I've pushed the changes to the macos branch if any macOS users want to try messing about with it themselves (not recommended). I'd still like a proper desktop release in the future.

![Screenshot 2021-06-01 at 18 16 18](https://user-images.githubusercontent.com/44349936/120365513-6bc19180-c306-11eb-8da1-f8810eff0070.png)

**Comment by mbnoimi** [comment]
Do you put a deadline for releasing desktop client?
I think Flutter for desktop is somehow mature now

**Comment by UnicornsOnLSD** [comment]
It won't be a thing by next release, but maybe the release after. There are two major things that I would have to do:

1. Add desktop support to just_audio. This shouldn't be too hard since it'll just be a wrapper around dart_vlc.
2. Create a new download plugin. flutter_downloader is basically entirely native code, so adding desktop support to that would be difficult. Also, flutter_download is a bit buggy with things like download callbacks (this is why download indicators are jank). I'll probably make the plugin in Dart instead of native code for better compatibility.

**Comment by mbnoimi** [comment]
> It won't be a thing by next release, 

I'm really glad to hear that from you and I wish to see the package in the next release.

**Comment by UnicornsOnLSD** [comment]
just_audio just got Windows and Linux support 👀

**Comment by UnicornsOnLSD** [comment]
Posting an update since this issue hasn't had one for a bit:

The Windows/Linux package I mentioned above has been discontinued as it wasn't production ready and the Linux implementation wasn't very good - it created a webview to play the audio in an `<audio>` tag. There have been some recent developments in https://github.com/ryanheise/just_audio/issues/332 with a proper win32-based package for Windows and an mpv-based package for Linux. The mpv package is a bit early on still but it looks very promising and I personally really like mpv so I have no objection using it. This all means that I can effectively cross of the GStreamer-based package I was going to make (referenced [here](https://www.reddit.com/r/jellyfin/comments/ufc1mv/finamp_roadmapvague_explanation_of_what_ive_got/)). Once I've created the new download package (#213), I will be able to make an initial desktop release. From there, I will create a proper desktop UI, which has the added benefit of improving Finamp on tablets.

**Comment by Fale** [comment]
Very nice to know :-).

Since that part is going to be revamped, it would be nice if - when the Linux Desktop arrives - a Linux Mobile is also provided, which is basically Linux Desktop with the UX of Android/mobile

**Comment by UnicornsOnLSD** [comment]
The UI will be adaptive so it should show the mobile form factor on mobile displays

**Comment by UnicornsOnLSD** [comment]
ARM support should be doable, setup was basically the same as x86 (this is running on Asahi Linux)

![Screenshot from 2022-06-14 12-35-27](https://user-images.githubusercontent.com/44349936/173569706-c0e84cb2-2f74-421e-a145-eef7507a5a0a.png)

**Comment by trymeouteh** [comment]
Please release this for Windows and MacOS as well.

For Linux, I would prefer it to be release as the following package types...

AUR
Pacstall
Flatpak

**Comment by UnicornsOnLSD** [comment]
Desktop support will likely come on all platforms at once, it'll just take a while. I should be able to publish on all of those package managers, and I'll also provide a deb, rpm, and a tar.gz of the build for other distros.

**Comment by jmshrv** [comment]
The main thing that needs to get implemented is #213, as that is needed for desktop.

I could just rip out downloads for desktop, but that would be an annoyingly involved process (in hindsight, I should have made it more easy to enable/disable downloads).

**Comment by baarkerlounger** [comment]
Ripping out or disabling downloads would also make it less useful for mobile linux.

**Comment by Gecked-Deck** [comment]
Well, for now, I'd love to have Finamp on desktop even without downloads. Downloading being implemeted in the future would be awesome (Especially for Linux Mobile, as mentioned) but I can live without it. Your call, of course, just glad to see there's an effort to get it on desktop at all

**Comment by pztrn** [comment]
Even without downloads, desktop version of Finamp will be very useful. I don't need downloads on my laptop because 99% of time I have working internet connection, as many other people too I presume.

**Comment by jmshrv** [comment]
Yeah its very unlikely that you're on a desktop without internet. There will still be a few things other than downloads that needs to be done for desktop (UI, ensuring audio works well), so I won't get this done now. I've started writing in detail what needs to be done for #213, see the linked document there for info.

**Comment by NaturalDevCR** [comment]
Hopefully this will see the light, it would be super helpful to have a windows client.

**Comment by Chaphasilor** [comment]
Okay, so since we have a new download system in the redesign, adding desktop support is feasible now. I've already got Finamp running on Windows (with the occasional crash), and linux support should also be possible now.  
If anyone could take a look into adding linux support (mainly packaging as snap/flatpack/appimage is needed), that would be much appreciated. Use the `desktop-beta` branch as a starting point.

Here are a few resources that might be useful for that:
- https://docs.flutter.dev/deployment/linux
- https://github.com/Merrit/flutter_flatpak_example
- https://github.com/AppImageCrafters/appimage-builder-flutter-example

Functionality wise, everything should work on linux. If it doesn't, please let me know!

**Comment by baarkerlounger** [comment]
@Chaphasilor I've been testing the `desktop-beta` branch with a view to helping with flatpak packaging. Downloads work fine but playback does not work for me (Debian Testing):

```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method success on channel vibrate)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
```

**Comment by Chaphasilor** [comment]
Oh, interesting! It seems like the issue isn't playback itself, but rather the vibration feedback when clicking a button. There should be playback options that don't yet give haptic feedback, like tapping a song in the song list to start an instant mix. Can you try if it works like that? When playing/pausing, don't use the now playing bar at the bottom, go to the player screen and pause from there to avoid vibration.  
If it works like that, we could simply add additional checks before trying to vibrate the device to avoid these exceptions.

**Comment by baarkerlounger** [comment]
@Chaphasilor also doesn't seem to work but for a different reason:

```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ProcessException: No such file or directory
  Command: mpv --idle --msg-level=all=no,ipc=v --no-video --no-audio-display audio-buffer=1 idle=yes --input-ipc-server=/tmp/MPV_Dart.sock
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      MPVPlayer._createMPVSubProcess (package:mpv_dart/src/mpv.dart:833)
#3      MPVPlayer.start (package:mpv_dart/src/mpv.dart:962)
<asynchronous suspension>
#4      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:67)
<asynchronous suspension>
```

**Comment by baarkerlounger** [comment]
Started flatpak packaging here: https://github.com/baarkerlounger/flathub/tree/finamp

The main things missing I think are:

- tar.gz of linux release bundle and sha256 file added to the release on this repo (better than pointing to mine)
- arm64 build
- Currently the app seems to require dbus permissions - any idea why that is?

**Comment by Chaphasilor** [comment]
@baarkerlounger do you have mpv installed? It's needed for `just_audio_mpv` to work: https://pub.dev/packages/just_audio_mpv#installation

**Comment by Chaphasilor** [comment]
> Currently the app seems to require dbus permissions - any idea why that is?

That's probably due to the dependency on [just_audio_mpris](https://pub.dev/packages/audio_service_mpris), which is used for populating the media session on linux (so that the currently playing track is shown in the media center).  
Is that a huge issue? 🤔

**Comment by baarkerlounger** [comment]
Hmm I have:

```bash
$ apt show mpv

Package: mpv
Version: 0.37.0-1
```

> That's probably due to the dependency on [just_audio_mpris](https://pub.dev/packages/audio_service_mpris)

Ah ok, I think there might be some special case things for mpris so I'll see how other media players have done it

**Comment by baarkerlounger** [comment]
Bundling MPV in the flatpak build and running that way gets files "playing" but there's no actual sound output. I notice from the logs:

```bash
flutter: Get org.mpris.MediaPlayer2.Player.Volume not implemented
```

**Comment by baarkerlounger** [comment]
It looks like it's an issue with the pipewire version in the latest freedesktop runtime. Related issues:

- https://github.com/mpv-player/mpv/issues/13312
- https://github.com/flathub/io.mpv.Mpv/issues/376
- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3848

Downgrading to 22.08 for now works. So the flatpak now builds and runs, downloading and playing tracks all works. At this point if you're happy to add a tar.gz of `build/linux/x64/release/bundle` and the aarch64 bundle to a release here, we could probably put a PR up to add Jellyfin to Flathub.

2 things I've noticed:

1. When you quit the player it doesn't kill the MPV process so it continues playing until manually killed (not flatpak specific a regular flutter build does this too)
2. The flatpak version doesn't maintain login state yet so you need to log in each time - how is that intended to work?

**Comment by Chaphasilor** [comment]
Okay, that sounds nice!  
The initial beta release is right around the corner, so I'd target this for the next release at the earliest. Possibly as an experimental feature, so if there's a way to manually download and install the flatpak I think that would suffice for now.

If the mpv process isn't properly killed upon exit, we should defintely investigate this. Maybe just_audio_mpv can do something about it, or maybe we can intercept a SIGTERM or something.  

Regarding the login state, that means that the database is not persisted for some reason. That not only breaks login, but also settings persistance and the whole download system. There are two database files, `finamp_db.hive` and `finamp_db.isar`. Is there any specific directory where those need to be placed to keep them across restarts?

**Comment by baarkerlounger** [comment]
Right got login persisting as well.

That sounds good, I'll wait for that release then. Once a PR is up the builder bot will build installable flatpaks that can be used to review. I've also noted in the app description that will be shown on Flathub that Linux build is "beta".

**Comment by Chaphasilor** [comment]
Regarding the playback issues, we can probably switch to [just_audio_media_kit](https://pub.dev/packages/just_audio_media_kit). That should work better and doesn't seem to have any external dependencies.

Can you confirm that shuffle with the current just_audio_mpv is broken? It seems like neither option does support shuffle properly, but I would like to make sure we're not missing out on a core feature by accident...

**Comment by baarkerlounger** [comment]
As far as I can tell shuffle works fine currently. One thing that's a little confusing is that most of the player controls like next/previous track etc only show up in the song view, not the overview view (screenshots to show what I mean).


![image](https://github.com/jmshrv/finamp/assets/5101747/315c5f90-1e37-4c30-87e0-e440dd221959)
![image](https://github.com/jmshrv/finamp/assets/5101747/e4b4d2b6-6aa2-49f3-bf7e-c6d8db7f75e0)

**Comment by Chaphasilor** [comment]
Interesting. I'm trying to get just_audio_media_kit to work and will see if that also supports shuffle...

The buttons are correct that way, an option to configure them will be introduced in a following update :)

**Comment by Chaphasilor** [comment]
Okay, got it to work on windows. It does work much better than just_audio_windows (doesn't crash when starting playback), but opening the queue and clicking the "shuffle" icon doesn't change the order of the tracks. You say that is different when using `just_audio_mpv`? Here's a video of how it looks for me:

https://github.com/jmshrv/finamp/assets/18015147/f6ccf174-26f8-4cd0-b052-6848d7ce1ef4

**Comment by baarkerlounger** [comment]
Ok yeah both versions behave the same for me (same as in your video), the "shuffle to queue" option appears to work though. I did have to `apt install libmpv-dev` with this version which the `just_audio_mpv` version I think did not require but on the plus side with this version closing the application does kill the audio process so that's good. 

Couple more things I've noticed:

- I couldn't get finamp to build on aarch64 because of isar (https://github.com/isar/isar/issues/876) not sure if you have a workaround for that?
- Closing the application window still leaves the terminal process running when run from terminal
- The window title should probably be capitalized on Linux (would fit other GTK apps better)

**Comment by baarkerlounger** [comment]
I see `v0.9.2-beta` has been announced now. Would it be possible to add Linux build bundles for x64 and (if possible) aarch64 to the release artifacts?

- cd build/linux/x64/release/
- tar -czf bundle.tar.gz bundle
- sha256sum bundle.tar.gz > bundle.tar.gz.sha256sum

**Comment by baarkerlounger** [comment]
Another issue (let me know if it would be better to make separate issues for these rather than using this as a Linux catch all) - it seems when you have a play queue it doesn't actually play through them, it stops after each track. The shuffle and repeat buttons are also missing tooltips.

**Comment by Chaphasilor** [comment]
Yeah I did notice that too on Windows. It sucks, because it essentially means we cannot use that library. I brought in up in their repo already, but no response yet...

**Comment by Chaphasilor** [comment]
Do you think we should go back to the old libs, or is there anything we can do about this? I don't have much time to deal with this, but would like to see this the light of day at some point ^^

**Comment by baarkerlounger** [comment]
@Chaphasilor assuming that's a question for me I don't think I can really answer it. I'm not sure if either lib is likely to fix this (or if the problem is even with them). I think my inclination would be to get a release out on Flathub and then iterate on it. Obviously there will be some bugs still but it's use-able already.

**Comment by Chaphasilor** [comment]
Do you mean a release with the current libs,  where playback stops after a single track? Don't you think that's too much of an issue?

**Comment by baarkerlounger** [comment]
I did yes, I guess that's up to you really. I don't think I know enough about Flutter dev to help much here but I did notice both of the `just_audio` libs look like they're not particularly actively developed/supported. Is using raw [media_kit](https://github.com/media-kit/media-kit) maybe an option?

**Comment by Chaphasilor** [comment]
@baarkerlounger as much trouble we might have with just_audio, it actually does its job really well. Even though it's pretty opinioned, it gives us access to a ton of platform-specific functionality, like Android Auto, that we couldn't get with media kit afaik. It's also super-tightly integrated into the app, and we don't have the resources to rip it out any time soon.

However, I managed to fix the bug with playback stopping after each track. I broke stopping in the process, but that's way less important and there's actually no UI to stop at the moment, so it should be fine.  
I pushed my changes to the branch, please try if it's also fixed on linux!

**Comment by baarkerlounger** [comment]
Nice, yep works for me. Not entirely sure what you mean by broke stopping but I guess that makes sense if you say it's not exposed in the UI.

**Comment by Chaphasilor** [comment]
Nice. I also managed to get media buttons and the media notification mostly working on Windows now. Do media buttons work properly on linux too?

**Comment by baarkerlounger** [comment]
Media buttons like Play, Pause, Next and Previous all work fine (on desktop, not tested on mobile yet). What notifications should there be?

**Comment by baarkerlounger** [comment]
The quick links on the right hand side seem a little janky. Clicking a letter further down the alphabet on a large library seems to scroll through each letter before getting there meaning it takes a couple of seconds to go where you intended rather than jumping straight to the right letter.

**Comment by Chaphasilor** [comment]
>  What notifications should there be?

Well there should be a way to see the currently playing track, including title, artist, artwork and playback progress via mpris. not sure where that is shown, probably depends on your desktop environment. It should be similar to the media notification that is shown on mobile platforms.

And the quick links ("fast scroller") are not working well in general, that's not a desktop issue. With our pagination setup it's not so simple to jump to a page directly, at least not in a way that still supports scrolling up and down to other letters (i.e. not just a plain filter).

I'm currently working on improving the just_audio_media_kit package to fix some playback issues. I think we'll introduce experimental desktop support with the 0.9.5 update. Just need to find someone to test macOS, but since that is natively supported by just_audio and audio_session, there shouldn't be any major hiccups.  
@jmshrv already found that auto discovery of local servers isn't working, but that should just be a permission issue.

**Comment by Nexusnui** [comment]
Is it to early to open another Issue to request a feature for the desktop version?
I thought that "always on top" could be useful for the desktop version.

**Comment by Chaphasilor** [comment]
There is a package that supports this: https://pub.dev/packages/window_manager#setalwaysontop  
We don't currently use it, but it seems to be quite powerful and useful for many different tasks, so I might actually add that :)  
Feel free to open an issue so I don't forget about it ^^

**Comment by AverageHelper** [comment]
> Just need to find someone to test macOS

@Chaphasilor Cloning now, will post here whether it works :P

**Comment by AverageHelper** [comment]
Ran `flutter pub get` and `flutter run` in the repo directory, and the app starts and seems to run just fine!

**Comment by AverageHelper** [comment]
Ah, seems toggling Favorite is broken. I get this error in the UI:

```
'package:finamp/models/finamp_models.dart': Failed assertion: line 790 pos 9: '_verifyEnums()': DownloadItemType.finampCollection BaseItemDtoType.unknown null
```

tho that could probs go into a separate issue.

**Comment by AverageHelper** [comment]
So it is! Thankies ^^

**Comment by viasux** [comment]
Just adding that windows support would be tremendously appreciated. Thanks for the work!

**Comment by Chaphasilor** [comment]
@viasux it's already working :)  
We just need to get it published to the Microsoft store ^^

**Comment by AverageHelper** [comment]
Would a macOS package be possible in releases?

**Comment by baarkerlounger** [comment]
https://flathub.org/apps/com.unicornsonlsd.finamp

**Comment by Chaphasilor** [comment]
We haven't "officially" released it yet, as there are still some bugs on desktop, especially on Linux. Once we do we'll close this :)  
Thanks for your efforts with packaging this for flathub!

**Comment by DomiStyle** [comment]
Awesome to see Finamp land on desktop, I have been using the client on Flathub for a few days now and things work pretty well.

Which library currently handles the MPRIS integration? I tried getting the MPRIS data to show on my Stream Deck and noticed that the MPRIS implementation doesn't follow the spec correctly:

https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties

`org.freedesktop.DBus.Properties.Get("org.mpris.MediaPlayer2.Player", "PlaybackStatus)` should return a string wrapped in a variant, instead it returns a string directly.

Seems to work fine with some integrations like KDE's media widget but it's still not to spec and probably should be fixed.

Should I create an issue on Finamp or the library for this?

**Comment by Chaphasilor** [comment]
@DomiStyle thanks for looking into it. https://github.com/flathub/flathub/pull/5297#discussion_r1621946633 should tell you what you need to know and what needs fixing :)

**Comment by DomiStyle** [comment]
@Chaphasilor Thanks for the info, reported it in the audio-service-mpris repo and should be fixed in the latest version (0.1.5).

**Comment by Chaphasilor** [comment]
@DomiStyle that should be bundled already, is the issue fixed?

**Comment by DomiStyle** [comment]
@Chaphasilor Looks good to me, the proper types are now returned.

**Comment by Chaphasilor** [comment]
I'll close this issue since there is support for Linux now (although rudimentary) and we have releases on Flathub and a few other package repos :)
