### ISSUE TITLE
'bool' is not a subtype of type 'LyricsAlignment'

### ISSUE THREAD

**Issue by 0elek** [UnicornsOnLSD/finamp#824]
Installed from flatpak on archlinux
jellyfin is on the latest version 

On startup i get this error:
```
[Startup/INFO] 2024-07-26 12:20:01.486279: App starting, logging initialized.
[ErrorApp/SEVERE] 2024-07-26 12:20:02.079838: type 'bool' is not a subtype of type 'LyricsAlignment' in type cast
		#0      FinampSettingsAdapter.read (package:finamp/models/finamp_models.g.dart:173)
		#1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
		#2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
		#3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
		#4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
		<asynchronous suspension>
		#5      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
		<asynchronous suspension>
		#6      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
		<asynchronous suspension>
		#7      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
		<asynchronous suspension>
		#8      Future.wait.<anonymous closure> (dart:async/future.dart:524)
		<asynchronous suspension>
		#9      setupHive (package:finamp/main.dart:221)
		<asynchronous suspension>
		#10     main (package:finamp/main.dart:80)
		<asynchronous 
```

**Comment by jmshrv** [comment]
Is this on a fresh install or are you upgrading? You may need to uninstall and reinstall, since that's the database upgrade failing for some reason.

**Comment by jmshrv** [comment]
> I think the issue could have been caused by an interrupted update.

Hopefully, otherwise I've messed up lol

**Comment by Chaphasilor** [comment]
Did you upgrade from 0.9.8 or 0.9.7? I think there were some issues because 0.9.7 was re-released multiple times since it's still in alpha, and that could've been an artifact from that...

**Comment by Chaphasilor** [comment]
I guess we'll see if it happens again ^^
